[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "npx playwright install && npm run build -- --base /modern-wagtail/"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
